version: '3.7'
services:
  web:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - frontend
  app:
    build: ./src/
    depends_on:
      - database
    volumes:
      - ./database:/app/database
    environment:
      ConnectionStrings__InspectionContext: Host=database;Database=postgres;Username=postgres;Password=mysecretpassword
    networks:
      - frontend
      - backend
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
