version: '3'
services:
  web:
    image: nginx:latest
    depends_on:
      - app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - frontend
  app:
    build: ./src/
    volumes:
      - ./database:/app/database
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
