version: '3'
services:
  web:
    image: nginx:latest
    depends_on:
      - app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  app:
    build: ./src/
    volumes:
      - ./database:/app/database
    ports:
      - 5000:5000
