version: '3'
services:
  web:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
  app:
    build: ./src/
    volumes:
      - ./database:/app/database
networks:
  frontend:
    driver: bridge