openapi: 3.0.0
info:
  title: API Specification
  description: クライアント-サーバー間のデータ通信仕様
  version: "1.0.0"
servers:
  - url: http://localhost/v1
    description: Development server

security:
  - api_key: []
  - users_auth:
    - write:users
    - read:users
