openapi: 3.0.0
info:
  title: API Specification
  description: クライアント-サーバー間のデータ通信仕様
  version: "1.0.0"
servers:
  - url: http://localhost/v1
    description: Development server
paths:
  /choice-templates:
    get:
      tags:
        - choice templates
      summary: Get all choice templates.
      description: Returns an array of ChoiceTemplate model
      parameters: []
      responses:
        '200':
          description: A JSON array of ChoiceTemplate model
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChoiceTemplate'
                example:
                  - choice_template_id: 1
                    choices:
                      - id: 1
                        description: OK
                      - id: 2
                        description: NG
                  - choice_template_id: 2
                    choices:
                      - id: 3
                        description: Yes
                      - id: 4
                        description: No
                      - id: 5
                        description: Unknown
    post: # POST
      tags:
        - users
      summary: Create a new User
      description: Create a new User
      parameters: []
      requestBody: # リクエストボディ
        description: user to create
        content:
          application/json:
            schema: # POSTするオブジェクト
              $ref: '#/components/schemas/User'
            example:
              id: 3
              name: Richard Roe
      responses:
        '201':
          description: CREATED
  /choice-templates/{choiceTemplateId}:
    get:
      tags:
        - choice templates
      summary: Get choiceTemplate by ID.
      description: Returns a single ChoiceTemplate model
      parameters:
        - name: userId
          in: path
          description: user id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single ChoiceTemplate model
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ChoiceTemplate'
                example:
                  choice_template_id: 1
                  choices:
                    - id: 1
                      description: OK
                    - id: 2
                      description: NG
components:
  schemas:
    ChoiceTemplate:
      type: object
      required:
        - choice_template_id
      properties:
        choice_template_id:
          type: integer
          format: int64
        choices:
          type: array
          items:
            $ref: "#/components/schemas/Option"
    Option:
      type: object
      required:
        - option_id
      properties:
        option_id:
          type: integer
          format: int64
        description:
          type: string

    User: # モデル名
      type: object # 型
      required: # 必須フィールド
        - id
      properties:
        id: # プロパティ名
          type: integer # 型
          format: int64 # フォーマット(int32, int64等)
        name:
          type: string
    Product:
      type: object
      required:
        - id
        - price
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Laptop
        price:
          type: integer
          example: 1200
security:
  - api_key: []
  - users_auth:
    - write:users
    - read:users
tags:
  - name: choice templates
    description: Access to ChoiceTemplates
  - name: users
    description: Access to Users
  - name: products
    description: Access to Products
