openapi: 3.0.0
info:
  title: API Specification
  description: クライアント-サーバー間のデータ通信仕様
  version: "1.0.0"
servers:
  - url: http://localhost/v1
    description: Development server
paths:
  /choice-templates:
    get:
      tags:
        - choice templates
      summary: Get all choice templates.
      description: Returns an array of ChoiceTemplate model
      parameters: []
      responses:
        "200":
          description: A JSON array of ChoiceTemplate model
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChoiceTemplate'
                example:
                  - choice_template_id: 1
                    choices:
                      - id: 1
                        description: OK
                      - id: 2
                        description: NG
                  - choice_template_id: 2
                    choices:
                      - id: 3
                        description: Yes
                      - id: 4
                        description: No
                      - id: 5
                        description: Unknown
        "400":
          description: バリデーションエラー or 業務エラー Bad Request
        "401":
          description: 認証エラー Unauthorized
        "403":
          description: 認可エラー Forbidden
        "503":
          description: システムエラー Internal Server Error

    post:
      tags:
        - choice templates
      summary: Create a new ChoiceTemplate
      description: Create a new ChoiceTemplate
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChoiceTemplate"
            example:
              choice_template_id: 0
              choices:
                - id: 1
                  description: OK
                - id: 2
                  description: NG
      responses:
        "201":
          description: 正常系（同期）Created
        "202":
          description: 正常系（非同期）Accepted
        "400":
          description: バリデーションエラー or 業務エラー Bad Request
        "401":
          description: 認証エラー Unauthorized
        "403":
          description: 認可エラー Forbidden
        "404":
          description: 一意制約違反エラー Conflict
        "409":
          description: 親リソースが存在しないエラー Not Found
        "503":
          description: システムエラー Internal Server Error
  /choice-templates/{choiceTemplateId}:
    get:
      tags:
        - choice templates
      summary: Get choiceTemplate by ID.
      description: Returns a single ChoiceTemplate model
      parameters:
        - name: choiceTemplateId
          in: path
          description: choice template ID
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single ChoiceTemplate model
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ChoiceTemplate'
                example:
                  choice_template_id: 1
                  choices:
                    - id: 1
                      description: OK
                    - id: 2
                      description: NG
        "400":
          description: バリデーションエラー or 業務エラー Bad Request
        "401":
          description: 認証エラー Unauthorized
        "403":
          description: 認可エラー Forbidden
        "404":
          description: 対象リソースが存在しない Not Found
        "503":
          description: システムエラー Internal Server Error
    put:
      tags:
        - choice templates
      summary: Updates a ChoiceTemplate
      description: ""
      parameters:
        - name: choiceTemplateId
          in: path
          description: choice template ID
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: 正常系（同期）OK
        "202":
          description: 正常系（非同期）Accepted
        "400":
          description: "Invalid ID supplied"
        "401":
          description: 認証エラー Unauthorized
        "403":
          description: 認可エラー Forbidden
        "404":
          description: "ChoiceTemplate not found"
        "503":
          description: システムエラー Internal Server Error
    delete:
      tags:
        - choice templates
      summary: Deletes a ChoiceTemplate
      description: ""
      parameters:
        - name: choiceTemplateId
          in: path
          description: choice template ID
          required: true
          schema:
            type: integer
      responses:
        "400":
          description: "Invalid ID supplied"
        "401":
          description: 認証エラー Unauthorized
        "403":
          description: 認可エラー Forbidden
        "404":
          description: "ChoiceTemplate not found"
        "503":
          description: システムエラー Internal Server Error
components:
  schemas:
    ChoiceTemplate:
      type: object
      required:
        - choice_template_id
      properties:
        choice_template_id:
          type: integer
          format: int64
        choices:
          type: array
          items:
            $ref: "#/components/schemas/Option"
    Option:
      type: object
      required:
        - option_id
      properties:
        option_id:
          type: integer
          format: int64
        description:
          type: string
tags:
  - name: choice templates
    description: Access to ChoiceTemplates
